// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FindMyValentine.Models;

public partial class MainDBContext : DbContext
{
    public MainDBContext(DbContextOptions<MainDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<MatchControl> MatchControls { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Account__3214EC077485AC19");

            entity.ToTable("Account");

            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.Username).IsRequired();
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Match__3214EC07DA3ADC8D");

            entity.ToTable("Match");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FemaleHint)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Level)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.MaleHint)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.StudentNumberFemale)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.StudentNumberMale)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<MatchControl>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MatchCon__3214EC07FE47C810");

            entity.ToTable("MatchControl");

            entity.Property(e => e.EndtDateTime)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Level).IsUnicode(false);
            entity.Property(e => e.StartDateTime)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Student__3214EC07FBC4EE86");

            entity.ToTable("Student");

            entity.Property(e => e.Course)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Hint).IsUnicode(false);
            entity.Property(e => e.Level)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Section)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.StudentName)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.StudentNumber)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Year)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}