// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FindMyValentine.Models;

public partial class MatchControl
{
    public int Id { get; set; }

    public bool IsActive { get; set; }

    public bool EndOverride { get; set; }

    public string StartDateTime { get; set; }

    public string EndtDateTime { get; set; }

    public string Level { get; set; }
}