// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FindMyValentine.Models;

public partial class Match
{
    public int Id { get; set; }

    public string StudentNumberMale { get; set; }

    public string StudentNumberFemale { get; set; }

    public string Level { get; set; }

    public bool Matched { get; set; }

    public string MaleHint { get; set; }

    public string FemaleHint { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }
}