// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FindMyValentine.Models;

public partial class Student
{
    public int Id { get; set; }

    public string StudentName { get; set; }

    public string StudentNumber { get; set; }

    public string Gender { get; set; }

    public string Course { get; set; }

    public string Year { get; set; }

    public string Section { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Level { get; set; }

    public string Hint { get; set; }
}